# Generated by Django 4.2.17 on 2026-03-02 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_alter_event_person_alter_familyevent_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='person_events', to='genealogy.image'),
        ),
        migrations.AddField(
            model_name='event',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='person_events', to='genealogy.source'),
        ),
        migrations.AddField(
            model_name='familyevent',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='family_events', to='genealogy.image'),
        ),
        migrations.AddField(
            model_name='familyevent',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='family_events', to='genealogy.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='citation_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('book', 'Book/Volume'), ('parish', 'Parish Record'), ('civil', 'Civil Record'), ('website', 'Website'), ('photo', 'Photo/Image'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='source',
            name='tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='genealogy.tree'),
        ),
        migrations.AlterField(
            model_name='source',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='genealogy.archive'),
        ),
    ]
